tools:
  mcp_call:
    signature: "mcp_call <tool_name> [<args_json>]"
    docstring: |
      Call an Unreal Engine MCP tool through HTTP request to the MCP server.
      
      Server URL: Configure via UNREAL_MCP_URL environment variable (default: http://localhost:9000/sse)
      
      Available tools include:
      - create_blueprint: Create a new Blueprint class
      - spawn_actor: Spawn an actor in the scene  
      - create_umg_widget_blueprint: Create a UMG widget
      - And many more...
      
      Examples:
      mcp_call create_blueprint '{{"name": "MyActor", "parent_class": "Actor"}}'
      mcp_call spawn_actor '{{"name": "TestActor", "type": "StaticMeshActor"}}'
    arguments:
      - name: tool_name
        type: string
        description: "The name of the MCP tool to call"
        required: true
      - name: args_json
        type: string
        description: "JSON string containing the arguments for the tool"
        required: false
        default: "{{}}"
  
  list_mcp_tools:
    signature: "list_mcp_tools"
    docstring: |
      List all available MCP tools from the Unreal Engine MCP server via HTTP.
      
      Server URL: Configure via UNREAL_MCP_URL environment variable (default: http://localhost:9000/sse)
    arguments: []