agent:
  model:
    name: openai/Qwen/Qwen2.5-VL-32B-Instruct
    api_base: http://132.239.95.133:8000/v1
    per_instance_cost_limit: 0
    total_cost_limit: 0
  templates:
    disable_image_processing: false
    system_template: |-
      You are a helpful assistant that can interact with a repository to solve tasks.

      You have access to the following tools:
      {{command_docs}}

      ## Working Environment
      - You are working in the repository directory: {{repo}}
      - Use relative paths when possible (e.g., ./file.py instead of absolute paths)
      - Always use simple, direct commands
      
      ## Command Guidelines
      - Use basic shell commands: ls, cat, find, grep, etc.
      - For file operations: use edit_file, str_replace_editor, or simple echo/cat
      - For MCP operations: use mcp_call <tool_name> [arguments]
      - Avoid complex command combinations or pipes that might hang
      
      ## Response Format
      Always format your responses exactly like this:
      
      DISCUSSION
      Explain what you're thinking and what you plan to do next.
      
      ```
      simple_command_here
      ```

      When the task is complete, use:
      ```
      exit
      ```
    instance_template: |-
      ## Task Description
      {{problem_statement}}

      ## Instructions  
      You are working in the repository: {{repo}}
      
      Your goal is to:
      1. Explore the current repository structure using basic commands (ls, find, cat)
      2. Check if MCP tools are available by trying: list_mcp_tools
      3. If MCP server is running, test commands like: mcp_call <tool_name>
      4. Document what you find and what capabilities are available
      
      Start with simple exploration. Use one command at a time.
      
      ## Available Commands
      - Basic shell: ls, cat, find, grep, pwd
      - MCP testing: list_mcp_tools, mcp_call <tool_name>
      - File operations: edit_file, str_replace_editor
    next_step_template: |-
      OBSERVATION:
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
  tools:
    execution_timeout: 15
    max_consecutive_execution_timeouts: 2
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
      UNREAL_MCP_URL: "http://localhost:8080"
    bundles:
      - path: tools/edit_anthropic
      - path: tools/image_tools
      - path: tools/unreal_mcp
    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
            You can do this with `git checkout -- /path/to/test/file.py`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: thought_action
  history_processors:
    - type: image_parsing
    - type: cache_control
      last_n_messages: 2
env:
  deployment:
    type: local
  repo:
    path: /home/koe/workspace